dataset_name: pizza10
model_name: AttnGAN
lmdb_file: data/pizza10/data.lmdb
retrieval_model: retrieval_model/runs/u9zyj9na/e27.pt
classifier: ingr_classifier/runs/1t5xrvwx/batch5000.ckpt
inception: inception_pizza10.pkl

ckpt_dir: AttnGAN/output/food_attn2_2020_11_10_11_51_01/Model/netG
ckpt_path: AttnGAN/output/food_attn2_2020_11_10_11_51_01/Model/netG/netG_epoch_01800.pth

# input_is_input: 1
# ckpt_dir: mpg/runs/2rrf2k9b
# ckpt_path: mpg/runs/2rrf2k9b/020000.pt

device: cuda
batch_size: 16
truncation: 1.0
size: 256
n_sample: 5000
seed: 9
