dataset_name: pizza10
model_name: mpg
retrieval_model: retrieval_model/runs/u9zyj9na/e27.pt
classifier: ingr_classifier/runs/pizza10/1t5xrvwx/batch5000.ckpt
inception: inception_pizza10.pkl

# model - mapping network
# ckpt_dir: mpg/runs/3ae90gw9
# ckpt_path: mpg/runs/3ae90gw9/040000.pt

# model - SLE
# ckpt_dir: mpg/runs/c1ysmsbe
# ckpt_path: mpg/runs/c1ysmsbe/040000.pt

# model - SLE* 
# ckpt_dir: mpg/runs/306bmus9
# ckpt_path: mpg/runs/306bmus9/040000.pt

# model - classification regularizer
# ckpt_dir: mpg/runs/1zg4fv6o
# ckpt_path: mpg/runs/1zg4fv6o/040000.pt

# model - matching
# ckpt_dir: mpg/runs/2ftkg1ww
# ckpt_path: mpg/runs/2ftkg1ww/040000.pt

# model - uncond
# ckpt_dir: mpg/runs/1s8jphpa
# ckpt_path: mpg/runs/1s8jphpa/040000.pt

# # model
ckpt_dir: mpg/runs/2y8walj3
ckpt_path: mpg/runs/2y8walj3/010000.pt

device: cuda
batch_size: 64
size: 256
truncation: 1.0
truncation_mean: 4096
n_sample: 5000
seed: 8